### ISSUE TITLE
Error in data.

### ISSUE THREAD

**Issue by jishnupdas** [datameet/covid19#14]
The data contained in data/mohfw.json has a slight error. the numbers for kerala are 

"report_time":"2020-07-30T08:00:00.00+05:30","cured":11365,"death":68,"confirmed":21797

"report_time":"2020-07-31T08:00:00.00+05:30","cured":12159,"death":70,"confirmed":2203,

"report_time":"2020-08-01T08:00:00.00+05:30","cured":13023,"death":73,"confirmed":23613

for date 31 there is a slight inconsistency maybe with the scraping

**Comment by thejeshgn** [comment]
Thanks @jishnupdas 

I think there is an error in the [source](https://github.com/datameet/covid19/blob/master/downloads/mohfw-backup/data_json/2020-07-31T08:00:00.00%2B05:30_md5_0872385af1a6f396a3ff2699e14d7d4a.json), I will find out the value and fix it. Thank for reporting.


	```
{
		"sno": "18",
		"state_name": "Kerala",
		"active": "10364",
		"positive": "21797",
		"cured": "11365",
		"death": "68",
		"new_active": "10074",
		"new_positive": "2203",
		"new_cured": "12159",
		"new_death": "70",
		"state_code": "32"
	},
```

**Comment by thejeshgn** [comment]
Its 22303. Fixed now.

**Comment by jishnupdas** [comment]
Thanks!

**Great work by the way on the repo!**
