### ISSUE TITLE
No Testing Data for 12-08-20

### ISSUE THREAD

**Issue by DnanaDev** [datameet/covid19#19]
@thejeshgn 
I'm running a cron job for a project that fetches the testing data from icmr_testing_status.json at 05:00 every morning. 

The job failed yesterday due to missing data for the day. Just wanted to know whether this was a one-off error or do I need to add some data validation to the script.

Appreciate the resource you guys have put together. 

Update : Error was in the script.

**Comment by thejeshgn** [comment]
What kind validation do you do. We can incorporate some.

**Comment by DnanaDev** [comment]
Since I parse the JSON to CSV, I perform validation using https://github.com/alimanfoo/csvvalidator
and this approach - https://www.kaggle.com/rtatman/dashboarding-with-notebooks-day-5

**Comment by DnanaDev** [comment]
The testing data for 12-08-20 is missing. Has there been a change in the update time/schedule or frequency ?

**Comment by thejeshgn** [comment]
Unless there is an issue. It should happen before 10AM
