### ISSUE TITLE
Start archiving cases per district published by each state

### ISSUE THREAD

**Issue by anandology** [datameet/covid19#9]
Identify the official source for each state and write a crawler to grab the press release/update every day.

Some of the sources are listed at:
https://telegra.ph/Covid-19-Sources-03-19

**Comment by anandology** [comment]
@thejeshgn where should the archives go? `archives/<state_code>/filename.pdf`?

**Comment by thejeshgn** [comment]
Can you check this once
https://github.com/datameet/covid-19-indian-state-reports

@aadityadar has been doing it manually for sometime. We can merge it here or we can keep it separate.
